### ISSUE TITLE
How can I use this sdk with my existing dropwizard application?

### ISSUE THREAD

**Issue by zkewal** [slackapi/java-slack-sdk#760] opened 2021-06-12 11:55 UTC
(Describe your issue and goal here)
Please point me towards any tutorials / implementation examples

My goal is to create an slack app which will accept slash command request from slack.
I have an existing server application in Dropwizard and would like to accept slack commands in a route like 'slack/events' on the same server.

**Comment by seratch** [comment] 2021-06-14 01:20
Hi @zkewal, thanks for asking the question!

I have some experience with Dropwizard a long time ago (when I was a Java/Scala backend engineer). As the framework is based on the Servlets, it should be relatively easy to have Bolt app as part of it. I will take some time to create an example app for you. 

I'm sure simple integration should work but one thing I have to mention is that, if your existing app has so many custom filters/intercepters, extensions, and any customization, those things may prevent smooth integration of Bolt and you may need to figure the cause out. It'd be appreciated if you could understand that we may not be able to help you out for the investigation process about your app specific parts.

Anyway, once I create a simple app, I will update you here.

**Comment by seratch** [comment] 2021-06-14 03:38
@zkewal I just created a minimum working example demonstrating how to integrate Bolt into a Dropwizard application: https://github.com/seratch/bolt-dropwizard-app 

Although the example app should have sufficient information in the code comments, let me add a few things:

This example places all the things [here](https://github.com/seratch/bolt-dropwizard-app/blob/main/src/main/java/example/SlackBoltApplication.java) for simplicity, but you can go with a more sophisticated way (e.g., moving the classes to component packages). 

The example app uses Dropwizard v2. Perhaps, most of my example code should be reusable in v1. If your apps still use v1 and you see some difference, please consult Dropwizard's documentation.

Lastly, my primary recommendation is to go with the **Solution 1: Use SlackAppServlet and register a plain servlet to the app** as it's proven. But I do understand if you may want to have all the endpoints as resources. In the case, **Solution 2** can be the right solution for you.

I hope this was helpful to you. If everything is clear now, would you mind closing this issue?

**Comment by seratch** [comment] 2021-06-19 00:46
👋 Let me close this issue but please feel free to write in whenever you have something further regarding this topic.

**Closed by seratch** 2021-06-19 00:46 UTC
Labels: project:bolt, question

**Comment by zkewal** [comment] 2021-06-20 08:26
@seratch Thank you for the code sample.

I have few additional questions:
1. Does this also take care of the slack user authentication part (Do I need an additional check to see if the request originated from Slack) ?
2. How do I get the email address attached to the slack account from which this request was originated?

**Comment by seratch** [comment] 2021-06-20 12:30
>Does this also take care of the slack user authentication part (Do I need an additional check to see if the request originated from Slack) ?

As long as you rely on the built-in feature, your app does not need to have any custom code for it. Bolt verifies requests from Slack (see https://api.slack.com/authentication/verifying-requests-from-slack for more details). Either passing token in `App` constructor or using authorization middleware associates proper OAuth access token with incoming requests.

>How do I get the email address attached to the slack account from which this request was originated?

Your app needs to have https://api.slack.com/scopes/users:read.email scope in addition to user.read. With this scope, your users.info / list API responses include email addresses as well. In Bolt apps, you can call the users.info API in a global middleware or it can call the API to store the additional user information in database in a background job.
