### ISSUE TITLE
bolt response not working

### ISSUE THREAD

**Issue by Harishkumarcratoflow** [slackapi/java-slack-sdk#1192] opened 2023-08-04 11:04 UTC
when i send a message in slack app i am getting      POST /slack/events 404 Not Found in ngrok .Everything is set up correctly is  there any issue with the code.this example was given by you i am currently trying it but i am not getting the response in slack.  

@WebServlet("/slack/events")
public class SlackAppController extends SlackAppServlet {
	public SlackAppController(App app) {
		super(app);
	}
@Bean
	public AppConfig loadSingleWorkspaceAppConfig() {
		return AppConfig.builder().singleTeamBotToken("REDACTED")
				.signingSecret("REDACTED").build();
	}

	@Bean
	public App initSlackApp(AppConfig config) {
		App app = new App(config);
		if (config.getClientId() != null) {
			app.asOAuthApp(true);
		}
		app.command("/crato", (req, ctx) -> {
			return ctx.ack(r -> r.text("Thanks!"));
		});
		return app;
	}
@SpringBootApplication
@ServletComponentScan
public class Slack2Application {

	public static void main(String[] args) {
		SpringApplication.run(Slack2Application.class, args);
	}

}

**Comment by filmaj** [comment] 2023-08-04 13:26
Hey @Harishkumarcratoflow , first I edited your issue as you posted your bot token and secret 😬 Please consider rotating those as those credentials are now compromised...

> POST /slack/events 404 Not Found in ngrok

When you say get this error "in ngrok", can you explain what you mean? Are you seeing errors in your ngrok process? Please provide any logs you have in order for us to help you.

In general it looks like the issue is that the Slack backend cannot send events to your application. I would guess this is due to your network setup or configuration, or how you have ngrok configured. Need more info to help you. Also please consider if your network environment has firewalls or proxies in place that would prevent ngrok from working.

**Comment by Harishkumarcratoflow** [comment] 2023-08-04 13:37
when i send a message in  a slack channel i am not getting response. In ngrok terminal it is showing 404 not found but the url got verified and also i gave the same url in slash command.Everything is setup correctly in slack.

**Comment by filmaj** [comment] 2023-08-04 13:48
Please post your slash command configuration and your ngrok configuration.

**Comment by Harishkumarcratoflow** [comment] 2023-08-04 13:51
here it is
![Screenshot (57)](https://github.com/slackapi/java-slack-sdk/assets/131237138/49a78312-f7a3-419f-ab9b-2ee75d99ff78)

**Comment by filmaj** [comment] 2023-08-04 13:55
Which URL got verified? Your Event Subscription URL or your Slash command URL? I do not believe Slash command URLs get verified.

What is the path portion of the ngrok URL you use for the slash command? Also, what is the full output if you run `curl -v <slash-command-ngrok-url>` ?

**Comment by filmaj** [comment] 2023-08-04 14:08
The slash command URL does not get verified in the same way.

Do requests to your slash command URL work? What is the full output if you run `curl -v <slash-command-ngrok-url>` ?

**Comment by Harishkumarcratoflow** [comment] 2023-08-04 14:09
![Screenshot (58)](https://github.com/slackapi/java-slack-sdk/assets/131237138/4e662ae5-beab-4db3-a8cd-6f3be8d9b136)

**Comment by filmaj** [comment] 2023-08-04 14:11
There you have it: ngrok is returning an HTTP 502 Bad Gateway error. Your ngrok is not set up properly.

**Comment by filmaj** [comment] 2023-08-04 14:14
I cannot help you with that as it is completely dependent on your computer, your local network setup, whether you have a proxy in place and other factors. Perhaps consider asking in ngrok support channels.

I will close this issue now but if you are able to set up ngrok properly and you are having issues with the Java project, feel free to open another issue.

**Closed by filmaj** 2023-08-04 14:14 UTC
Labels: needs info, question

**Comment by Harishkumarcratoflow** [comment] 2023-08-04 14:15
yes i will check

**Comment by Harishkumarcratoflow** [comment] 2023-08-04 14:22
yes it is running locally
