### ISSUE TITLE
No way to get thread id (ThreadTs) from MessageFileShareEvent

### ISSUE THREAD

**Issue by teamstand-rishabh** [slackapi/java-slack-sdk#511] opened 2020-07-09 15:33 UTC
I want to reply on the same thread but not getting threadTs
with MessageEvent its working fine
ChatPostMessageResponse response = ctx.client().chatPostMessage(r -> r.channel(ctx.getChannelId())
					.threadTs(req.getEvent().getThreadTs()).text(":wave: How are you?"));

**Comment by seratch** [comment] 2020-07-09 15:58
You can use event.ts for it. req.getEvent().getTs() should work for you.

**Comment by teamstand-rishabh** [comment] 2020-07-09 16:00
Yes I have tried that but its not working. Its not posting message in same thread.

**Comment by seratch** [comment] 2020-07-10 05:59
Just in case, I just tried it out and confirmed using `event.ts` for `thread_ts` param in `chat.postMessage` calls works for me.

To help you out, we need more information. What was the outcome of `chat.postMessage`? Did you get an error code in its response?

**Comment by teamstand-rishabh** [comment] 2020-07-10 07:39
I am using this
`app.event(MessageFileShareEvent.class, (payload, ctx) -> {
			System.out.println(payload.getEvent().getType());
			System.out.println(payload.getEvent().getSubtype());
			// FileSharedEvent event = payload.getEvent();
		
			ChatPostMessageResponse response = ctx.client()
					.chatPostMessage(r -> r.channel(ctx.getChannelId()).threadTs(payload.getEvent().getTs())
							.text("File shared"));
			
			
			return ctx.ack();
		});`

But instead of replying "File shared" on thread , its sending the parent message (the message which caused the event) in the channel

**Comment by teamstand-rishabh** [comment] 2020-07-10 07:45
If I am using fresh message. Its working fine. In that case event ts and thread ts are same.
But when I reply on existing thread, its not working as expected.

**Comment by seratch** [comment] 2020-07-10 07:59
Thanks for elaborating on your issue. Now I understand it. 

I'll escalate this feedback to the teams concerned. Unfortunately, I cannot tell whether the server-side may add `thread_ts` for file sharing event payloads in the future.

A possible implementation idea I can share at this moment would be utilizing https://api.slack.com/methods/conversations.replies every time you receive this type of event to fetch `thread_ts`. I do understand this doesn't sound desirable to you but I'd appreciate it if you could go with the workaround.

**Comment by seratch** [comment] 2020-07-24 01:52
@teamstand-rishabh I might overlook something two weeks ago but now I'm getting `thread_ts` in the `file_share` message events. This PR https://github.com/slackapi/java-slack-sdk/pull/522 I just created seems to be a solution for your use case. Please let me know if I misunderstand your issue here.

**Comment by seratch** [comment] 2020-07-27 22:14
fixed by #522

**Closed by seratch** 2020-07-27 22:14 UTC
Labels: project:slack-api-model, project:slack-app-backend
