### ISSUE TITLE
ChatUnfurlRequest preview option is missing; automatic preview generation has encoding issues

### ISSUE THREAD

**Issue by cathywise** [slackapi/java-slack-sdk#963] opened 2022-04-07 03:49 UTC
I've noticed that in the previews for our link unfurls that show in the message composer, the ampersands are showing as `&amp;`:

<img width="294" alt="Screen Shot 2022-03-10 at 09 55 18" src="https://user-images.githubusercontent.com/73504859/162087941-f080408f-98a4-4b59-8728-563d0edd834b.png">

I had guessed that we might be able to improve this by supplying a `preview` as [the chat.unfurl docs](https://api.slack.com/methods/chat.unfurl) suggest, but there's no option to do so in the [Java SDK](https://github.com/slackapi/java-slack-sdk/blob/main/slack-api-client/src/main/java/com/slack/api/methods/request/chat/ChatUnfurlRequest.java). Is this intentional? Is providing the `preview` likely to provide a workaround?

#### The Slack SDK version

1.20.1

#### Java Runtime version

openjdk 15.0.2 2021-01-19

#### OS info

ProductName:	macOS
ProductVersion:	12.3
BuildVersion:	21E230
Darwin Kernel Version 21.4.0: Mon Feb 21 20:34:37 PST 2022; root:xnu-8020.101.4~2/RELEASE_X86_64

#### Steps to reproduce:

I'm using the SDK like this:

```java
var unfurls = new HashMap<String, ChatUnfurlRequest.UnfurlDetail>();
for (var link : req.getEvent().getLinks()) {
    System.out.println(link.getUrl());
    var title = "Collaborate & Create Amazing Graphic Design for Free";
    var description = """
            Create beautiful designs with your team.
            Use Canva's drag-and-drop feature and layouts to design,
            share and print business cards, logos, presentations and more.""";
    var unfurlDetail = new ChatUnfurlRequest.UnfurlDetail();
    unfurlDetail.setAuthorIcon("https://slack-integration-assets-public.canva.com/link-unfurling-canva-logo.png");
    unfurlDetail.setAuthorName("Canva");
    unfurlDetail.setTitle(title);
    unfurlDetail.setTitleLink(link.getUrl());
    unfurlDetail.setText(description);
    unfurlDetail.setImageUrl("https://slack-integration-assets-public.canva.com/link-unfurling-default-preview.jpg");
    unfurlDetail.setColor("#00C4CC");
    unfurlDetail.setFallback(description);
    var openInCanvaButton =
            Action.builder()
                    .type(Action.Type.BUTTON)
                    .text("Open In Canva")
                    .url(link.getUrl())
                    .build();
    unfurlDetail.setActions(asActions(openInCanvaButton));
    unfurls.put(link.toString(), unfurlDetail);
}
var unfurlRequest =
        ChatUnfurlRequest.builder()
                .token(botToken.token)
                .unfurls(unfurls)
                .channel(req.getEvent().getChannel())
                .ts(req.getEvent().getEventTs())
                .build();
var res = slackClient.chatUnfurl(unfurlRequest).join();
if (res.isOk()) {
```

I'm sorry for not providing a full minimal example. I spent a good amount of time trying to build one, but was unable to make something that could actually unfurl urls using Bolt and socket mode 😢. If you have a template or example you know works, I'd be happy to implement this inside it.

#### Expected result:

`&`

#### Actual result:

`&amp;`

### Requirements

Please make sure if this topic is specific to this SDK. For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to the those rules.

**Comment by seratch** [comment] 2022-04-07 04:00
Hi @cathywise, thanks for taking the time to report this issue and I'm sorry for the lack of the option in this SDK. We will resolve this issue in the next patch version (by the end of this week).

**Comment by seratch** [comment] 2022-04-07 05:40
Hi @cathywise, I've checked this and submitted a pull request adding the parameter. However, when it comes to your use case, perhaps, the way to correct the title of the auto-unfurl title would be to set the top-level `title`, not the one under `preview` object. 

In the pull request https://github.com/slackapi/java-slack-sdk/pull/964, I've added a unit test as below:
```java
var unfurls = new HashMap<String, ChatUnfurlRequest.UnfurlDetail>();
var detail = new ChatUnfurlRequest.UnfurlDetail();
detail.setTitle("The top-level title (set by chat.unfurl)");
detail.setPreview(ChatUnfurlRequest.UnfurlDetailPreview.builder()
  .title(plainText("The title in the preview set (set by chat.unfurl)"))
  .subtitle(plainText("The subtitle in the preview (set by chat.unfurl)"))
  .iconUrl("https://assets.brandfolder.com/pmix53-32t4so-a6439g/original/slackbot.png")
  .build()
);
unfurls.put(url, detail);

var unfurlResponse = slack.methods().chatUnfurl(ChatUnfurlRequest.builder()
  .token(botToken)
  .channel("C11111")
  .ts("111.222")
  .unfurls(unfurls)
  .build());
```

The appearance in the channel looks like this:
<img width="400" src="https://user-images.githubusercontent.com/19658/162127877-f98d82b9-34b6-4641-853e-3a2b4d93f7cd.png">

This means that you can use only `title` for the workaround to the auto-unfurl title issue. We are sorry for the confusing document there. I hope this was helpful to you.

**Comment by cathywise** [comment] 2022-04-07 22:20
Thanks so much for the fast response and fix! Really appreciated 😄 

We are already using the top-level title field in our unfurl, and it displays correctly within the channel. But when the user is writing the message, the link unfurl within the message composer shows the `&` as `&amp;`. Perhaps this isn't related to the SDK, but an issue with the Slack message editor?

Here's what ours looks like in the channel (once sent):
<img width="613" alt="Screen Shot 2022-04-08 at 08 19 29" src="https://user-images.githubusercontent.com/73504859/162328896-b51e2e77-dfc4-4ecb-be7f-3550842a6a1a.png">

And this is in the composer (before sending):
<img width="294" alt="Screen Shot 2022-03-10 at 09 55 18" src="https://user-images.githubusercontent.com/73504859/162328965-8b56800b-83f2-47bf-81e2-243a018d8bf2.png">

**Comment by seratch** [comment] 2022-04-08 04:55
Hi @cathywise, I am sorry for the misbehavior of the built-in feature but I've implemented a workaround on my own. I've confirmed that your app can receive link_shared events with `"channel": "COMPOSER"` type.

```json
{
  "type": "link_shared",
  "user": "U111",
  "channel": "COMPOSER",
  "message_ts": "U111-XXX",
  "links": [
    {
      "url": "https://www.canva.com/",
      "domain": "www.canva.com"
    }
  ],
  "source": "composer",
  "unfurl_id": "U111-XXX",
  "is_bot_user_member": true,
  "event_ts": "1649393193.206389"
}
```

Here is a simple bolt-java app.

```java
package samples;

import com.slack.api.bolt.App;
import com.slack.api.bolt.AppConfig;
import com.slack.api.bolt.socket_mode.SocketModeApp;
import com.slack.api.methods.request.chat.ChatUnfurlRequest;
import com.slack.api.model.event.LinkSharedEvent;

import java.util.HashMap;
import java.util.Map;

public class UnfurlingApp {

  public static void main(String[] args) throws Exception {
    App app = new App(AppConfig.builder().singleTeamBotToken(System.getenv("SLACK_BOT_TOKEN")).build());
    app.event(LinkSharedEvent.class, (payload, ctx) -> {
      app.executorService().submit(() -> {
        try {
          Map<String, ChatUnfurlRequest.UnfurlDetail> unfurls = new HashMap<>();
          for (LinkSharedEvent.Link link : payload.getEvent().getLinks()) {
            ChatUnfurlRequest.UnfurlDetail unfurl = new ChatUnfurlRequest.UnfurlDetail();
            unfurl.setTitle("Collaborate & Create Amazing Graphic Design for Free");
            unfurl.setText("text text text");
            unfurls.put(link.getUrl(), unfurl);
          }
          ctx.client().chatUnfurl(r -> r
            .channel(payload.getEvent().getChannel())
            .ts(payload.getEvent().getMessageTs())
            .source(payload.getEvent().getSource())
            .unfurls(unfurls)
          );
        } catch (Exception e) {
          ctx.logger.error("Failed to unfurl the links", e);
        }
      });
      return ctx.ack();
    });

    String appToken = System.getenv("SLACK_APP_TOKEN");
    SocketModeApp socketModeApp = new SocketModeApp(appToken, app);
    socketModeApp.start();
  }
}
```

This app handles the unfurling events as below. Setting the top-level title this way works as you expect.
<img width="300" src="https://user-images.githubusercontent.com/19658/162367245-7ac7a392-9d1a-4547-b060-bbd45822be1f.png">

The app needs the following permissions.

```yaml
display_information:
  name: canva-domain-unfurl-app
features:
  bot_user:
    display_name: canva-domain-unfurl-app
  unfurl_domains:
    - www.canva.com
oauth_config:
  scopes:
    user:
      - links:read
    bot:
      - links:read
      - links:write
settings:
  event_subscriptions:
    user_events:
      - link_shared
    bot_events:
      - link_shared
  socket_mode_enabled: true
```

Lastly, the built-in behavior should be improved. I will escalate the issue to the product team later on. With that, let me close this issue now 🙇

**Closed** 2022-04-08 04:55 UTC
Labels: bug, project:slack-api-client
