### ISSUE TITLE
Encountering MultiTeamsAuthorization error with Spring Boot 3 example app when OAuth settings are enabled

### ISSUE THREAD

**Issue by tzuanw** [slackapi/java-slack-sdk#1171] opened 2023-06-14 23:35 UTC
Hello, I'm trying to build a multi workspace Slack App using Springboot 3.  The example code I'm using is provided [here](https://github.com/slackapi/java-slack-sdk/tree/main/bolt-spring-boot-examples/spring-boot-3)

But for some reason, when I run this program, I encounter this error:

```
[main] INFO org.eclipse.jetty.server.AbstractConnector - Started ServerConnector@5745ca0e{HTTP/1.1, (http/1.1)}{0.0.0.0:3000}
[main] INFO org.eclipse.jetty.server.Server - Started Server@4e07b95f{STARTING}[11.0.15,sto=0] @416ms
[main] INFO com.slack.api.bolt.jakarta_jetty.SlackAppServer - ⚡️ Bolt app is running!
**[qtp775514090-34] INFO com.slack.api.bolt.middleware.builtin.MultiTeamsAuthorization - auth.test result: null, io error: null, api error: null**
```

I am setting all the appropriate secrets as detailed in the README but for some reason getting the above MultiTeamsAuthorization error.

#### The Slack SDK version

```gradle
plugins {
    id 'org.springframework.boot' version '3.0.0'
    id 'io.spring.dependency-management' version '1.1.0'
    id 'java'
}
group = 'com.example'
version = '0.0.1-SNAPSHOT'
repositories {
    mavenCentral()
    mavenLocal()
}
dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'com.slack.api:bolt-jakarta-servlet:[1.27,)'
}
```

#### Java Runtime version

Running this within intelliJ using :
temurin-17.jdk

#### OS info

(Paste the output of `sw_vers && uname -v` on macOS/Linux or `ver` on Windows OS)
```
ProductName:            macOS
ProductVersion:         13.1
BuildVersion:           22C65
Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000
```

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., pom.xml/build.gradle))

1. Simply follow all the steps in the README 
2. Comment out line [13](https://github.com/slackapi/java-slack-sdk/blob/104c70f0952653290b54319ea4c84556d69c6808/bolt-spring-boot-examples/spring-boot-3/src/main/java/example/SlackApp.java#L13) and enable line [23](https://github.com/slackapi/java-slack-sdk/blob/104c70f0952653290b54319ea4c84556d69c6808/bolt-spring-boot-examples/spring-boot-3/src/main/java/example/SlackApp.java#L23)
3. Run the Application within IDEA

#### Expected result:

I would expect the '/' command to run normally and not run into this MultiTeamsAuthorization error

#### Actual result:

(Tell what actually happened with logs, screenshots)
<img width="1135" alt="image" src="https://github.com/slackapi/java-slack-sdk/assets/104949063/10bf331c-0630-4ab2-af92-68b19f6fb7d6">

### Requirements

Please make sure if this topic is specific to this SDK. For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you agree to those rules.

**Comment by seratch** [comment] 2023-06-15 02:06
Hi @tzuanw, thanks for asking the question!

It seems that you're trying to enable the OAuth installation flow for your app. When your app enables the OAuth installation flow rather than the single installation using the button on the app admin page, your app always needs to be installed from the /slack/install URL. Additionally, the installation data must be stored in your app's `InstallationService`.
* https://github.com/slackapi/java-slack-sdk/blob/main/bolt/src/main/java/com/slack/api/bolt/service/InstallationService.java
* https://github.com/slackapi/java-slack-sdk/blob/v1.29.2/bolt/src/main/java/com/slack/api/bolt/App.java#L475 

The reason why your app is available in your Slack workspace without going through the steps should be that you've already installed the app from the admin page before enabling the OAuth flow. In this case, while your app is not yet ready for OAuth-enabled token resolution, you can use slash commands, etc., which are enabled by non-OAuth installations (meaning installing your app from the admin page).

To resolve the error you're encountering, you can go through the OAuth installation flow, whcih starts at `https://{your publci domain like ngrok.io}/slack/install` and completes at `/slack/oauth_redirect`. If everything goes well, you will see the success page and the installation data will be stored in your local machine (with the defalt settings, your app stores tokens etc. [using local file system](https://github.com/slackapi/java-slack-sdk/blob/main/bolt/src/main/java/com/slack/api/bolt/service/builtin/FileInstallationService.java); for prodution apps, you can switch to other built-in ones or your own one).

I hope this helps.

**Comment by tzuanw** [comment] 2023-06-15 15:49
@seratch thanks so much for your insightful response. I followed the install path `https://{your public domain like ngrok.io}/slack/install`, clicked on Allow button to grant necessary permissions but ended up here:
![image](https://github.com/slackapi/java-slack-sdk/assets/104949063/577eb2bb-2d52-4d07-9096-b840fa2f12a8)

Maybe I am missing another Oauth configuration step? thank you!

**Comment by seratch** [comment] 2023-06-16 00:11
@tzuanw Calling `App#asOAuthApp(true)` is necessary to enable OAuth related built-in endpoints: https://github.com/slackapi/java-slack-sdk/blob/v1.29.2/bolt-spring-boot-examples/spring-boot-3/src/main/java/example/SlackApp.java#L39-L41

Please double-check that you've properly configured clientId, clientSecret, and required other arguments in AppConfig.

**Comment by tzuanw** [comment] 2023-06-20 14:12
Thank you @seratch again. It turns out I did use all the correct credentials but the issue was that I had to specify the exact redirect URL. Slack Oauth did not like it when I specified more than 1:
![image](https://github.com/slackapi/java-slack-sdk/assets/104949063/918e3be5-931a-4206-9297-2bc8c3b26da4)

And installs started to work after I only used one URL:
<img width="1037" alt="image" src="https://github.com/slackapi/java-slack-sdk/assets/104949063/eaee8b61-345f-4eee-b4a1-d39d0589fe89">

**Comment by seratch** [comment] 2023-06-20 14:18
@tzuanw Great to hear that you've figure the cause out! If you still want to have two redirect URLs, you can either pass the "SLACK_APP_REDIRECT_URI" env variable or explicitly call the `AppConfig#redirectUri(String)` method to set a specific one.

It seems that everything is clear now, so let me close this issue now. Thanks again for writing in!

**Closed by seratch** 2023-06-20 14:18 UTC
Labels: question, project:bolt
