### ISSUE TITLE
Rich text support clarification

### ISSUE THREAD

**Issue by mechanik0s** [slackapi/java-slack-sdk#876] opened 2021-10-27 18:39 UTC
@seratch 
> Unfortunately, any 3rd party Slack apps are unable to populate the rich_text blocks. As mentioned in this changelog, those blocks are available only for Slack client apps (Desktop, Web Browser, iOS, Android)' WYSIWYG editors.

Sorry can you quote exactly place in changelog that said this?

So, I found that rich text blocks works fine with `chat.unfurl` method and I can't understand a reason why it doesn't supported in `postMessage`. Maybe supporting in plans?
Can you clarify, please?

_Originally posted by @mechanik0s in https://github.com/slackapi/java-slack-sdk/issues/736#issuecomment-953207694_

**Comment by srajiang** [comment] 2021-11-01 20:16
Hi @mechanik0s 👋 

I've confirmed that apps/bots should not be supplying rich text blocks to API methods (so `chat.postMessage` not being supported is expected behavior), so the changelog announcement is correct. Devs shouldn't expect `chat.unfurl` to accept rich text blocks. If that's the current behavior, it is due to a bug with the platform that will be closed in time (timeline I don't have further details on at the moment). 

I would recommend modifying your setup to minimize the possibility of hiccups when the bug is eventually closed.

I realize that's probably not the answer you were hoping for, but hopefully it is at least clarifying. I'm going to close this issue up for now!

**Closed** 2021-11-01 20:16 UTC
Labels: question
