### ISSUE TITLE
Slash actions are working but block actions are not, due to "hashed timestamp blocks.actions not ok: dispatch_failed"

### ISSUE THREAD

**Issue by briankurilko** [slackapi/java-slack-sdk#1189] opened 2023-08-01 18:04 UTC
I have a slack app that displays a button with a block action after running a slash command. The slash command works, but the block action returns a 403. The request that the button push makes does not make it to my Java Spring Boot Bolt servlet, it receives a 403 without ever making a request to my Java application. 

When running Slack from within the browser, I receive the following error in the network tab when I try to execute the slack action:

```bash
{"subtype":"missing_subtype","message":"hashed timestamp blocks.actions not ok: dispatch_failed","stack":"dispatch_failed: hashed timestamp blocks.actions not ok: dispatch_failed\n    at Bn._onNotOk (https://a.slack-edge.com/bv1-10/gantry-v2-shared.ecc6e6b.min.js?cacheKey=gantry-1690818443:1:179606)\n    at Bn.resolve (https://a.slack-edge.com/bv1-10/gantry-v2-shared.ecc6e6b.min.js?cacheKey=gantry-1690818443:1:179211)\n    at Bn._onLoad (https://a.slack-edge.com/bv1-10/gantry-v2-shared.ecc6e6b.min.js?cacheKey=gantry-1690818443:130:92498)"}
```

Does anyone know why this might be happening? Not sure if it matters, but I'm also running this app behind a corporate proxy (I've set up the correct `http.proxyHost`, `http.proxyPort`, and `http.nonProxyHosts` system properties to work with the proxy with the Bolt API, though).

#### The Slack SDK version

```bash
+--- com.slack.api:bolt-jakarta-servlet:1.30.0
|    +--- com.slack.api:slack-api-model:1.30.0
|    +--- com.slack.api:slack-api-client:1.30.0
|    |    +--- com.slack.api:slack-api-model:1.30.0 (*)
|    +--- com.slack.api:slack-app-backend:1.30.0
|    |    +--- com.slack.api:slack-api-model:1.30.0 (*)
|    |    +--- com.slack.api:slack-api-client:1.30.0 (*)
|    \--- com.slack.api:bolt:1.30.0
|         +--- com.slack.api:slack-api-model:1.30.0 (*)
|         +--- com.slack.api:slack-api-client:1.30.0 (*)
|         +--- com.slack.api:slack-app-backend:1.30.0 (*)
+--- com.slack.api:bolt-jakarta-jetty:1.30.0
|    +--- com.slack.api:slack-api-model:1.30.0 (*)
|    +--- com.slack.api:slack-api-client:1.30.0 (*)
|    +--- com.slack.api:slack-app-backend:1.30.0 (*)
|    +--- com.slack.api:bolt:1.30.0 (*)
|    +--- com.slack.api:bolt-jakarta-servlet:1.30.0 (*)
+--- com.slack.api:bolt-jakarta-servlet:1.30.0 (n)
+--- com.slack.api:bolt-jakarta-jetty:1.30.0 (n)
```

#### Java Runtime version

```bash
openjdk version "17.0.6" 2023-01-17 LTS
```

#### OS info

```bash
ProductName:            macOS
ProductVersion:         13.5
BuildVersion:           22G74
Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000
```

#### Spring Boot versions:

```bash
 id 'org.springframework.boot' version '3.0.0'
id 'io.spring.dependency-management' version '1.0.11.RELEASE'
```

#### Steps to reproduce:

Here's my code for building the view:
<img width="1142" alt="image" src="https://github.com/slackapi/java-slack-sdk/assets/98776353/ddfa0a0e-63b0-4694-9094-a4c27ae9e9c5">

Here's my code for registering the button action:
<img width="836" alt="image" src="https://github.com/slackapi/java-slack-sdk/assets/98776353/147af068-ab62-4bb4-9ac6-26c87572cb76">

And here's my code for the event handler itself:
<img width="790" alt="image" src="https://github.com/slackapi/java-slack-sdk/assets/98776353/4276e078-403c-42eb-bc65-b53247207306">

Lastly, here is my servlet code, which should be the entrypoint of my project:
<img width="517" alt="image" src="https://github.com/slackapi/java-slack-sdk/assets/98776353/94188e82-21d0-40f2-a93c-f1e40ea20a10">

#### Expected result:

I expect the button to make a call to the block action I've configured in my Spring Boot backend and do the block action.

#### Actual result:

<img width="612" alt="image" src="https://github.com/slackapi/java-slack-sdk/assets/98776353/e24aad63-0b7c-4594-8329-cf9e6ed436ef">

A call is **never made to my Spring Boot backend** (at least for the block action - the slash action works), and by looking at the network tab, the request fails with the following payload:
<img width="1728" alt="image" src="https://github.com/slackapi/java-slack-sdk/assets/98776353/a5184f48-6cc0-4080-9702-ef5e9a93a2ec">

Does anyone have any ideas as to why this is happening?

**Comment by seratch** [comment] 2023-08-02 00:48
Hi @briankurilko, could you double-check if you've configured **Interactivity & Shortcuts** section in the app configuration page (meaning `https://api.slack.com/apps/{you app ID here}`). You need to enable the interactivity and set a valid **Request URL** to handle interactive user action requests. The "dispatch_failed" error code indicates Slack API server does not know where to send a request.

**Comment by briankurilko** [comment] 2023-08-02 03:04
Hi @seratch, the following is a screenshot of my **Interactivity & Shortcuts** page: 
<img width="709" alt="image" src="https://github.com/slackapi/java-slack-sdk/assets/98776353/ab40fa7b-8232-4efb-99e6-d05c9afbcb14">

Also, here's what the configuration for the (working) slash command looks like: 
<img width="706" alt="image" src="https://github.com/slackapi/java-slack-sdk/assets/98776353/fda2b5ea-8fb3-439b-9928-0d7a88284101">

As you can see, both the slash command and the interactivity and shortcuts request URL are the same (https://outpost.labs.ford.com/slack/events). I'm unsure why it works for slash commands, but does not for interactivity commands.

**Comment by seratch** [comment] 2023-08-02 03:11
Here is a simple working example app for Spring Boot 3 users. Checking the difference in your app may be helpful to figure the cause out: https://github.com/slackapi/java-slack-sdk/tree/main/bolt-spring-boot-examples/spring-boot-3

**Comment by briankurilko** [comment] 2023-08-02 15:34
@seratch one thing we tried was deploying our application to a separate server running on Pivotal Cloud Foundry instead of GCP - when we did this, all block actions worked. Similarly, when using ngrok to test our app, the block actions work as well. Could there be some kind of weird routing thing that Slack is trying to do when trying to connect to GCP application?

**Comment by seratch** [comment] 2023-08-02 23:17
@briankurilko Some aspect in your GCP environment may prevent your app from properly receiving the request data, but I cannot guess anything so far. We are unable to help you out for GCP-specific questions. Please head to their communities or forum spaces. It seems that I don't have anything further I can do for you. Would you mind if I close this issue now?

**Comment by briankurilko** [comment] 2023-08-03 01:55
@seratch Ok sure, you can close it.

**Closed** 2023-08-03 01:56 UTC
Labels: question, project:bolt
