### ISSUE TITLE
Custom field do not seem to trigger any event if updated alone

### ISSUE THREAD

**Issue by silk-bahamut** [slackapi/java-slack-sdk#1094] opened 2022-11-26 08:28 UTC
I'm trying to react to some custom field in the user profile but the user_change or user_profile_changed event are not triggered on custom field.

I've added a birthdate as a user edit custom field in the admin and in the user change event I'm listing the value of the custom field.
When updating main field, everything works fine, I have an event but when I only change a custom field I do not seem to get an event, is it the expected behavior?

#### The Slack SDK version

[INFO] +- com.slack.api:bolt-servlet:jar:1.26.1:compile
[INFO] |  +- com.slack.api:slack-api-model:jar:1.26.1:compile
[INFO] |  +- com.slack.api:slack-api-client:jar:1.26.1:compile
[INFO] |  +- com.slack.api:slack-app-backend:jar:1.26.1:compile
[INFO] |  \- com.slack.api:bolt:jar:1.26.1:compile

#### Java Runtime version

openjdk 17.0.5 2022-10-18 LTS
OpenJDK Runtime Environment Corretto-17.0.5.8.1 (build 17.0.5+8-LTS)
OpenJDK 64-Bit Server VM Corretto-17.0.5.8.1 (build 17.0.5+8-LTS, mixed mode, sharing)

#### OS info

Microsoft Windows [Version 10.0.19045.2251]

#### Steps to reproduce:

1. Creating a custom field in slack admin
2. Subscribing to user_change event and/or user_profile_changed
3. Edit in the profile only the new custom field

#### Expected result:

Receive an event of user change.

#### Actual result:

No event at all.

**Comment by seratch** [comment] 2022-11-28 03:29
Hi @silk-bahamut, thanks for taking the time to report this and we're sorry for the unexpected API behavior.

I also confirmed no event delivery for the properties except "Contact information" section. I've submitted an internal escalation to the server-side engineering team. We'll update you once we've got a new information on this matter.

**Comment by seratch** [comment] 2022-11-28 23:32
Hi @silk-bahamut, I've checked this issue with the server-side engineering teams, and found that no event delivery for custom property updates is an expected behavior.

Also, there is no great workaround and I cannot tell anything about the possibility of the enhancement. So sorry about this but it'd be appreciated if you could understand this. Since we don't have anything to share for now, let us close this issue.

**Closed by seratch** 2022-11-28 23:32 UTC
Labels: project:bolt, project:slack-app-backend, server-side-issue
