### ISSUE TITLE
How to run Bolt in JHipster applications

### ISSUE THREAD

**Issue by FlorianRuen** [slackapi/java-slack-sdk#729] opened 2021-04-20 06:53 UTC
### Description

Hello There,

I'm trying to implement a Slack Bot server using Spring Boot and Jhipster as frameworks (because I got another API, and I want it to be the same server, easily to maintain)

So I just the folow the documentation : 
[1] : https://api.slack.com/start/building/bolt-java
[2] : the code example for spring boot = https://github.com/slackapi/java-slack-sdk/tree/master/bolt-spring-boot-examples

But when I fire the slash command example /hello, I got an error **"dispatch_failed"**, and I got an error in my Java app terminal (so the command reach the endpoint successfully)

The error in my terminal is something IllegalStateException : STREAMED
(The full error code is pasted is : https://pastebin.com/gi7nHbK7)

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [ x ] question
- [ ] documentation related
- [ ] example code related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [ x ] I've read and understood the [Contributing guidelines](https://github.com/slackapi/bolt/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [ x ] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [ x ] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

package version: com.slack.api:bolt:1.7.1

node version: 12.17.0

OS version(s): Ubuntu 18.04

#### Steps to reproduce:

1. Generate a new Jhipster project using Java / No front client / PostgreSQL database engine
2. Add the @Bean and @Configuration to launch the slack bolt server
3. Configure chat bot and send slash command to get error

#### Expected result:

I expected an answer to be :wave Hello from JAVA API !

#### Actual result:

I got "dispatch_failed" error in slack and error in my terminal

#### Attachments:

None

Hope  someone can help me,

Thanks for your help,

Kind regards,
Florian

**Comment by seratch** [comment] 2021-04-20 07:07
Hi @FlorianRuen, could you share a bit more details of your project? Particularly, I'm interested in your build settings and how you use Spring's annotations in the app. There are a few things to know about Spring Boot integration:

* Bolt properly works with Spring Boot 2.2 or newer versions
* Bolt app endpoints do not work with any filters/intercepters that read the request body beforehand

Also, I have been answering many questions about Spring Boot. Some of these issues may be helpful for figuring your issue out: https://github.com/slackapi/java-slack-sdk/issues?q=is%3Aissue+spring+boot+

**Comment by seratch** [comment] 2021-04-20 07:47
@FlorianRuen I've confirmed Bolt for Java works in a simple JHipster project. All I did are:

* Create a new project using the generator-jhipster
* Add `@org.springframework.boot.autoconfigure.SpringBootApplication.ServletComponentScan` annotation to the `@SpringBootApplication` wired class
* Add `SlackAppController` class in the rest package
* Start the app and use the path `/slack/events` for Request URLs

```java
package hello.web.rest;

import com.slack.api.bolt.App;
import com.slack.api.bolt.servlet.SlackAppServlet;
import com.slack.api.model.event.AppMentionEvent;

import javax.servlet.annotation.WebServlet;

@WebServlet("/slack/events")
public class SlackAppController extends SlackAppServlet {
    // You can make App instance available as a bean component
    private static App buildApp() {
        // export SLACK_BOT_TOKEN=
        // export SLACK_SIGNING_SECRET=
        App app = new App();
        app.event(AppMentionEvent.class, (req, ctx) -> ctx.ack());
        app.command("/hello", (req, ctx) -> ctx.ack("What's up?"));
        return app;
    }

    public SlackAppController() {
        this(buildApp());
    }

    public SlackAppController(App app) {
        super(app);
    }
}
```

I hope doing the same works for your apps.

**Comment by FlorianRuen** [comment] 2021-04-20 07:56
@seratch I do exactly what is on the sample spring boot project (because Jhipster doesn't change the project, it's only a way to help us to generate entities or so one). I already got @ServletComponentScan, my @WebServlet and the configuration for the Slack Bolt (I just don't use export but the code from example config.setBotToken ...) for now.

In one of your message, you said "Bolt doesn't work with filters / intercepters", but by default in my project, I think I got some kind of HttpSecurity which can block my request to refuse it (which cause an error and a dispatch failed)

Here is my SecurityConfiguration class, do you think that one of that line can block my request with the previous message ?
https://pastebin.com/2fr8T5ir

Thanks for your help

**Comment by seratch** [comment] 2021-04-20 08:00
@FlorianRuen 
>PS : I'm using Jhipster 6.3.1, Spring Boot 2.1.8.RELEASE

As I mentioned in the above comment, Bolt supports only Spring Boot 2.2 and newer versions. I'm sorry to say this but we are not planning to support Spring Boot 2.1. Please consider upgrading the Spring Boot version to a newer version.

**Comment by FlorianRuen** [comment] 2021-04-20 18:36
@seratch I try to update my full project to Spring boot 2.4.4 and I got the following error when sending a slash command

```
java.util.concurrent.TimeoutException: Idle timeout expired: 30001/30000 ms
        at org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:171)
        at org.eclipse.jetty.io.IdleTimeout.idleCheck(IdleTimeout.java:113)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

I already get this kind of error with my previous version of Spring. Do you have any idea on how to fix this ?

Thanks for your help on it

**Comment by seratch** [comment] 2021-04-20 20:52
@FlorianRuen I've never seen this type of errors with my example apps and I don't have any information about the threads your app has. I would recommend creating a brand-new application and trying the steps I've shared above. Checking the difference between your current app and the new simple app may be helpful to identify the cause of your issue.

**Comment by FlorianRuen** [comment] 2021-04-20 21:52
@seratch I will try but to reproduce, I just run jhipster to init a new project (latest version of generator jhipster to be able to jze Spring 2.4.4) and add the lines from exemple. 

No other changes cause this error

Checking all files can take a lot of time, but if needed...

**Comment by FlorianRuen** [comment] 2021-04-21 12:05
Update : I also try to remove all CORS filter or something else which can block the request (allow everything), and I got exactly the same error

**Comment by seratch** [comment] 2021-06-03 01:26
Hi @FlorianRuen, have you figured your issue out? 

As I shared above, a simple Jipster project surely works with Bolt framework. Thus, my recommendation is to start with a simplest project first, add Bolt dependencies and see it works, and then your other extra dependencies.

If you don't have any further topics that are specific to the Bolt framework, would you mind closing this issue?

**Comment by seratch** [comment] 2021-06-19 00:46
👋 Let me close this issue but please feel free to write in whenever you have something further regarding this topic.

**Closed by seratch** 2021-06-19 00:46 UTC
Labels: project:bolt, question
