### ISSUE TITLE
Spring Boot @Webservlet returns 401 when processing event from interactive Block (Spring Boot 2.1.5)

### ISSUE THREAD

**Issue by carlospalmaroldan** [slackapi/java-slack-sdk#710] opened 2021-03-15 20:08 UTC
I am trying to click on a button generated by the block kit builder and do something on the java side with it.
Whenever I click on said button I get a 401. I managed to debug and see that the class responsible for this is SlackSignature inside the method isValid and that what happens is that the signature sent in the header X-slack-signature is different from the one generated by the class. 

I had to manually get the payload parameter in another class because whenever I sent the request directly to SlackAppServlet the body would be null. To clarify:
```
@WebServlet("/slack/events")
public class SlackAppController extends SlackAppServlet {
    private static final Logger LOGGER = LogManager.getLogger(SlackAppServlet.class);

    private final App app;

    private final SlackAppServletAdapter adapter;

    private SlackRequestParser requestParser;

    public SlackAppController(App app) {
        super(app);
        this.app = app;
        this.adapter = new SlackAppServletAdapter(app.config());
        this.requestParser = new SlackRequestParser(app.config());
    }

    protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws IOException {
            super.doPost(req, resp);   
    }
}
```
This will lead to: 
```
public class SlackAppServlet extends HttpServlet {
    @Generated
    private static final Logger log = LoggerFactory.getLogger(SlackAppServlet.class);
    private final App app;
    private final SlackAppServletAdapter adapter;

    public App getApp() {
        return this.app;
    }

    public SlackAppServlet(App app) {
        this.app = app;
        this.adapter = new SlackAppServletAdapter(app.config());
    }

    protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws IOException {
        Request slackReq = this.adapter.buildSlackRequest(req);
        if (slackReq != null) {
            try {
                Response slackResp = this.app.run(slackReq);
                this.adapter.writeResponse(resp, slackResp);
            } catch (Exception var5) {
                log.error("Failed to handle a request - {}", var5.getMessage(), var5);
                resp.setStatus(500);
                resp.setContentType("application/json");
                resp.getWriter().write("{\"error\":\"Something is wrong\"}");
            }
        }

    }
}
```
But the method buildSlackRequest returns null. 

### Reproducible in:

```bash
mvn dependency:tree | grep com.slack.api
gradle dependencies | grep com.slack.api
java -version
sw_vers && uname -v # or `ver`
```

#### The Slack SDK version

[INFO] +- com.slack.api:bolt-servlet:jar:1.4.1:compile
[INFO] |  +- com.slack.api:slack-api-model:jar:1.4.1:compile
[INFO] |  +- com.slack.api:slack-api-client:jar:1.4.1:compile
[INFO] |  +- com.slack.api:slack-app-backend:jar:1.4.1:compile
[INFO] |  \- com.slack.api:bolt:jar:1.4.1:compile

#### Java Runtime version

java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

#### OS info

Microsoft Windows [Version 10.0.19041.630]

#### Steps to reproduce:

1. We create a webservlet using Spring boot to process the request sent when the user clicks on a button in the slack chat:

```

@WebServlet("/slack/events")
public class SlackAppController extends SlackAppServlet {
    private static final Logger LOGGER = LogManager.getLogger(SlackAppServlet.class);


    private final App app;


    private final SlackAppServletAdapter adapter;

    private SlackRequestParser requestParser;

    public SlackAppController(App app) {
        super(app);
        this.app = app;
        this.adapter = new SlackAppServletAdapter(app.config());
        this.requestParser = new SlackRequestParser(app.config());
    }

    protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws IOException {
        SlackHttpServletRequestWrapper requestWrapper = new SlackHttpServletRequestWrapper(req);
        String retry = req.getHeader("X-Slack-Retry-Num");
        if (retry == null) {
            super.doPost(requestWrapper, resp);
        }
    }
}
```

2. As explained before we need to create our own class to get the payload parameter:
```
    public class SlackHttpServletRequestWrapper extends HttpServletRequestWrapper {
      public SlackHttpServletRequestWrapper(HttpServletRequest request) {
          super(request);
      }
    
      @Override
      public BufferedReader getReader() throws IOException {
          if (MediaType.APPLICATION_FORM_URLENCODED_VALUE.equals(getContentType())) {
              String payload = "payload=" + URLEncoder.encode(getParameter("payload"), "UTF-8");
              return new BufferedReader(new StringReader(payload));
          }
          return super.getReader();
      }
    }
```

3. Inside RequestVerification class the line that validates the X-slack-signature header returns false:
```
public class RequestVerification implements Middleware {
    @Generated
    private static final Logger log = LoggerFactory.getLogger(RequestVerification.class);
    private final Verifier verifier;

    public RequestVerification(Verifier verifier) {
        this.verifier = verifier;
    }

    public Response apply(Request req, Response resp, MiddlewareChain chain) throws Exception {
        if (MiddlewareOps.isNoSlackSignatureRequest(req.getRequestType())) {
            return chain.next(req);
        } else if (req.isValid(this.verifier)) {
            return chain.next(req);
        } else {
            String signature = req.getHeaders().getFirstValue("X-Slack-Signature");
            log.info("Invalid signature detected - {}", signature);
            return Response.json(401, "{\"error\":\"invalid request\"}");
        }
    }
}
```

the line is else if (req.isValid(this.verifier)).

#### Expected result:

The request should proceed through the different middlewares without problems and end up executing the eventHandler programmed by the library's user.

#### Actual result:

401 because req.isValid returns false.

### Requirements

  
        <dependency>
            <groupId>com.slack.api</groupId>
            <artifactId>bolt-servlet</artifactId>
            <version>1.4.1</version>
        </dependency>

**Comment by mwbrooks** [comment] 2021-03-15 20:32
Hey @carlospalmaroldan, thanks for the detailed message and steps to reproduce!

I'm not as experienced with the Java SDK, but I wanted to ask simple question before our core maintainer @seratch is able to look at this issue.

Since you're handling a button interaction, are you using the `@WebServlet("/interactive")` annotation? The code sample above looks as though it's using a `/slack/events` annotation. You can find more info in https://github.com/slackapi/java-slack-sdk/issues/642#issuecomment-737617800, which explains the recommended way to annotate `@WebServlet`.

Sorry if this suggestion is way off mark, but I thought I'd offer it in case it helps unblock you!

**Comment by carlospalmaroldan** [comment] 2021-03-15 20:43
Hello there @mwbrooks . Thanks for taking a look at the issue. #642 does not mention a problem with directly using SlackAppServlet. I was trying that but the body of the request ended up being null. Also the annotation is WebServlet, what's inside the parenthesis is just the path.

**Comment by seratch** [comment] 2021-03-15 21:08
@mwbrooks 
Thanks for jumping in! The reason why I suggested using `@WebServlet("/interactive")` in #642 was the original code in the issue was trying to use the path.

@carlospalmaroldan 
Do you have any particular reason to have `SlackHttpServletRequestWrapper` in your app? [The servlet adapter parses the request body for you](https://github.com/slackapi/java-slack-sdk/blob/v1.6.2/bolt-servlet/src/main/java/com/slack/api/bolt/servlet/SlackAppServletAdapter.java#L31
). You don't need to have your own layer only for it. If you need to have a wrapper for some reason, it's totally fine to add some extra logic in the class **as long as your logic does not modify the request body and headers related to the signature verification**. The request body value should not be modified at all. If the raw string request body data is not exactly the same with the original data, the signature verification fails (even if the meaning of the data is the same).

**Comment by carlospalmaroldan** [comment] 2021-03-15 21:13
"You don't need to have your own layer only for it."
I do. Here's why:
![image](https://user-images.githubusercontent.com/21181510/111222038-4e9fe100-85a9-11eb-9259-a10c65a62fe8.png)
This is what happens when passing the request directly to the class SlackAppServlet

**Comment by seratch** [comment] 2021-03-15 21:19
@carlospalmaroldan 
What version of Spring Boot do you use? Unfortunately, 2.1 or older versions are not supported: https://github.com/slackapi/java-slack-sdk/issues/582

Another possible cause of this is that, as I mentioned in #642,
>The important thing is that your controller should not consume the InputStream of request body data to construct Java objects. The reason for this is that Slack's request signature verification requires access to the raw string request body (the one which is not modified at all). So, you cannot use any built-in body parsers enabled by Spring Boot framework for this endpoint.

please make sure if there is no built-in / 3rd party configuration (you may have global configuration by annotations) that enables automatic request data parsers.

If none of the above conjecture  is correct and if an issue can arise with the latest Spring Boot, I will try to reproduce your issue later. It'd be appreciated if you could provide a minimum working example that reproduces your issue.

**Comment by carlospalmaroldan** [comment] 2021-03-15 21:40
```
<!-- Spring boot. -->
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.1.5.RELEASE</version>
        <relativePath />
    </parent>
```

**Comment by seratch** [comment] 2021-03-15 21:44
@carlospalmaroldan This is our bad. Although the GitHub issue is publicly visible, there is no mention about the supported Spring Boot versions in the document. I will update the document later. Hope your Spring Boot upgrade to a newer version will go smoothly!

**Comment by seratch** [comment] 2021-03-16 01:54
Updated the document: https://github.com/slackapi/java-slack-sdk/commit/4447c3ea7d5d5be70caa2a8c6296f14e04a0ae57

Let me close this issue now.

**Closed by seratch** 2021-03-16 01:54 UTC
Labels: project:bolt, question
