### ISSUE TITLE
MessageDeletedEvent Java bug when a threaded message with Tombstone us deleted. 

### ISSUE THREAD

**Issue by EnricoVoss** [slackapi/java-slack-sdk#784] opened 2021-07-15 11:58 UTC
(Describe your issue and goal here)

### Reproducible in:

Message Event listener throws error when a thread is deleted when the main message was already deleted (Tombstone)

```
Error:
[socket-mode-message-processor-worker-22] ERROR com.slack.api.bolt.socket_mode.SocketModeApp - Failed to handle a request: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at path $.previous_message
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at path $.previous_message
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:1003)
	at com.google.gson.Gson.fromJson(Gson.java:975)
	at com.slack.api.bolt.util.EventsApiPayloadParser.buildEventPayload(EventsApiPayloadParser.java:58)
	at com.slack.api.bolt.App.runHandler(App.java:1010)
	at com.slack.api.bolt.App.lambda$runMiddleware$2(App.java:925)
	at com.slack.api.bolt.middleware.builtin.IgnoringSelfEvents.apply(IgnoringSelfEvents.java:97)
	at com.slack.api.bolt.App.runMiddleware(App.java:925)
	at com.slack.api.bolt.App.lambda$runMiddleware$3(App.java:928)
	at com.slack.api.bolt.middleware.builtin.SingleTeamAuthorization.apply(SingleTeamAuthorization.java:87)
	at com.slack.api.bolt.App.runMiddleware(App.java:928)
	at com.slack.api.bolt.App.lambda$runMiddleware$3(App.java:928)
	at com.slack.api.bolt.middleware.builtin.RequestVerification.apply(RequestVerification.java:27)
	at com.slack.api.bolt.App.runMiddleware(App.java:928)
	at com.slack.api.bolt.App.lambda$runMiddleware$3(App.java:928)
	at com.slack.api.bolt.middleware.builtin.SSLCheck.apply(SSLCheck.java:51)
	at com.slack.api.bolt.App.runMiddleware(App.java:928)
	at com.slack.api.bolt.App.run(App.java:539)
	at com.slack.api.bolt.socket_mode.SocketModeApp.lambda$buildSocketModeClient$0(SocketModeApp.java:37)
	at com.slack.api.socket_mode.SocketModeClient.processMessage(SocketModeClient.java:355)
	at com.slack.api.socket_mode.SocketModeClient.lambda$initializeMessageProcessorExecutor$0(SocketModeClient.java:157)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at path $.previous_message
	at com.google.gson.internal.bind.JsonTreeReader.expect(JsonTreeReader.java:163)
	at com.google.gson.internal.bind.JsonTreeReader.beginObject(JsonTreeReader.java:88)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215)
	... 30 more
```

`mvn dependency:tree | grep com.slack.api`:

```xml
   	<dependency>
   	  	<groupId>com.slack.api</groupId>
  		<artifactId>bolt</artifactId>
  		<version>1.8.1</version>   	
   	</dependency>
   	 <dependency>
  		<groupId>com.slack.api</groupId>
  		<artifactId>bolt-servlet</artifactId>
  		<version>1.8.1</version>
  	</dependency>
  	  	<dependency>
  		<groupId>com.slack.api</groupId>
  		<artifactId>bolt-jetty</artifactId>
  		<version>1.8.1</version>
  	</dependency>
  	  <dependency>
  		<groupId>com.slack.api</groupId>
  		<artifactId>bolt-socket-mode</artifactId>
  		<version>1.8.1</version>
  	</dependency>
```

```bash
java -1.8
```

#### The Slack SDK version

(Paste the output of `mvn dependency:tree | grep com.slack.api` or `gradle dependencies | grep com.slack.api`)

#### Java Runtime version

(Paste the output of `java -version`)

#### OS info

(Paste the output of `sw_vers && uname -v` on macOS/Linux or `ver` on Windows OS)

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., pom.xml/build.gradle))

1.
2.
3.

#### Expected result:

(Tell what you expected to happen)

#### Actual result:

(Tell what actually happened with logs, screenshots)

### Requirements

Please make sure if this topic is specific to this SDK. For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to the those rules.

**Comment by seratch** [comment] 2021-07-15 15:59
Hi @EnricoVoss, thanks a lot for taking the time to report this and we're sorry for the error situation where there is no workaround on your app side.

>Expected BEGIN_OBJECT but was BEGIN_ARRAY at path $.previous_message

The event payload data class expects an object for the `previous_message` [this way](https://github.com/slackapi/java-slack-sdk/blob/v1.8.1/slack-api-model/src/main/java/com/slack/api/model/event/MessageDeletedEvent.java#L27). However, it seems that the actual payload can have an array with the key **only in this case**.

I am wanting to have a correct test data for reproducing this situation. I'm guessing the type of `previous_message` should be `List<Message>` in this scenario but am not 100% sure about it yet. If possible, may I ask you to provide the actual JSON data that caused the error in your app? I know perhaps you don't have such, though...

To address this issue, the JSON parser needs to have something like [this](https://github.com/slackapi/java-slack-sdk/blob/main/slack-api-client/src/main/java/com/slack/api/util/json/GsonAuditLogsDetailsChangedValueFactory.java) for the event payload.

**Comment by EnricoVoss** [comment] 2021-07-15 19:53
Hi @seratch 

This is the payload causing the error:
MessageDeletedEvent

EventsApiPayloadParser.BoltEventPayload(token=RZ3Pq2U2sLeG23XeqcMqBIQY, enterpriseId=E010X9P37H6, teamId=T013956SEUD, apiAppId=A0285KAK13L, type=event_callback, authedUsers=null, authedTeams=null, authorizations=[Authorization(enterpriseId=E010X9P37H6, teamId=null, userId=U0282JP3SHK, isBot=true, isEnterpriseInstall=true)], isExtSharedChannel=false, eventId=Ev02880WKVJN, eventTime=1626378646, eventContext=2-message-T013956SEUD-A0285KAK13L-C027YV4FGBY, event=MessageDeletedEvent(type=message, subtype=message_deleted, channel=C027YV4FGBY, hidden=true, deletedTs=1626378603.002000, previousMessage=MessageDeletedEvent.Message(clientMsgId=null, type=message, subtype=tombstone, user=USLACKBOT, team=null, edited=null, text=This message was deleted., blocks=null, attachments=null, starred=false, pinnedTo=null, reactions=null, ts=1626378603.002000), eventTs=1626378646.003700, ts=1626378646.003700, channelType=group))

**Comment by seratch** [comment] 2021-07-15 21:38
@EnricoVoss Thanks for your prompt reply!

>previousMessage=MessageDeletedEvent.Message(clientMsgId=null, type=message, subtype=tombstone, user=USLACKBOT, team=null, edited=null, text=This message was deleted., blocks=null, attachments=null, starred=false, pinnedTo=null, reactions=null, ts=1626378603.002000)

I'm curious about how you converted the JSON data to this Java object. According to the exception you've shared, the JSON parser (gson) cannot build the Java object due to the incompatibility of the JSON data. If you have the JSON string data, would you mind sharing it with us?

**Comment by EnricoVoss** [comment] 2021-07-16 04:09
@seratch 
I see you are based in Japan, we can have a quick call and I can rund you through my code so you can see when the error occurs. I am available for the next 2 hours, if you have some time?

**Comment by EnricoVoss** [comment] 2021-07-16 04:46
@seratch You can recreated like this:


setup MessageDeletedEvent listener 

`			app.event(MessageDeletedEvent.class, (payload, ctx) -> {
				System.out.println("MessageDeletedEvent\n"+payload);
				  return ctx.ack();
				});`

go in channel an write a message and a thread to the message. 
Remove the main message so it leave a tombstone, now delete the threaded message. and you should get the error and the payload causing the error. 

Thank you for your help on this one.

**Comment by EnricoVoss** [comment] 2021-08-10 11:58
Hi Kazuhiro.

Sorry for my late response but I was on annual leave for a couple of weeks.
I have updated the bolt SDK versions to 1.9.0 but I am still getting the
very same error.

I still get the same error message when I delet a threaded message with a
tombstone. Do you have some time to look into this? We can set up a meeting
sometime this week?

[socket-mode-message-processor-worker-22] ERROR
com.slack.api.bolt.socket_mode.SocketModeApp - Failed to handle a request:
java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY
at path $.previous_message
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException:
Expected BEGIN_OBJECT but was BEGIN_ARRAY at path $.previous_message
at
com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
at
com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
at
com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
at com.google.gson.Gson.fromJson(Gson.java:932)
at com.google.gson.Gson.fromJson(Gson.java:1003)
at com.google.gson.Gson.fromJson(Gson.java:975)
at
com.slack.api.bolt.util.EventsApiPayloadParser.buildEventPayload(EventsApiPayloadParser.java:58)
at com.slack.api.bolt.App.runHandler(App.java:1010)
at com.slack.api.bolt.App.lambda$runMiddleware$2(App.java:925)
at
com.slack.api.bolt.middleware.builtin.IgnoringSelfEvents.apply(IgnoringSelfEvents.java:97)
at com.slack.api.bolt.App.runMiddleware(App.java:925)
at com.slack.api.bolt.App.lambda$runMiddleware$3(App.java:928)
at
com.slack.api.bolt.middleware.builtin.SingleTeamAuthorization.apply(SingleTeamAuthorization.java:87)
at com.slack.api.bolt.App.runMiddleware(App.java:928)
at com.slack.api.bolt.App.lambda$runMiddleware$3(App.java:928)
at
com.slack.api.bolt.middleware.builtin.RequestVerification.apply(RequestVerification.java:27)
at com.slack.api.bolt.App.runMiddleware(App.java:928)
at com.slack.api.bolt.App.lambda$runMiddleware$3(App.java:928)
at com.slack.api.bolt.middleware.builtin.SSLCheck.apply(SSLCheck.java:51)
at com.slack.api.bolt.App.runMiddleware(App.java:928)
at com.slack.api.bolt.App.run(App.java:539)
at
com.slack.api.bolt.socket_mode.SocketModeApp.lambda$buildSocketModeClient$0(SocketModeApp.java:37)
at
com.slack.api.socket_mode.SocketModeClient.processMessage(SocketModeClient.java:355)
at
com.slack.api.socket_mode.SocketModeClient.lambda$initializeMessageProcessorExecutor$0(SocketModeClient.java:157)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
at
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
at
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was
BEGIN_ARRAY at path $.previous_message
at
com.google.gson.internal.bind.JsonTreeReader.expect(JsonTreeReader.java:163)
at
com.google.gson.internal.bind.JsonTreeReader.beginObject(JsonTreeReader.java:88)
at
com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215)
... 30 more

Thank you.



Kind Regards

Enrico Voss

Consultant System Engineering
Global Network and Technology
Verizon Business Group

O 004969972686460
Rebstockerstrasse 59
Germany
Frankfurt



On Tue, 20 Jul 2021 at 14:20, Kazuhiro Sera ***@***.***>
wrote:

> Closed #784
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_slackapi_java-2Dslack-2Dsdk_issues_784&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=1wJkRHrOQWKuCmMkVqCZcBmKHwdcJRk5Vs2bg7sJSsw&m=PxCbUy8EpM7XQL78ZQAQOFTHQw13-TxY3hB4e_WrAGg&s=XmrNZ7sRz-6fivEFLx5Gm29fmQhJz4jlGeOrpfdjjmA&e=>
> via #791
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_slackapi_java-2Dslack-2Dsdk_pull_791&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=1wJkRHrOQWKuCmMkVqCZcBmKHwdcJRk5Vs2bg7sJSsw&m=PxCbUy8EpM7XQL78ZQAQOFTHQw13-TxY3hB4e_WrAGg&s=cxMPVM0BS7e-OPWVyOhVug_hQRXe-QzeCIx1j2pjQRU&e=>
> .
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_slackapi_java-2Dslack-2Dsdk_issues_784-23event-2D5043962276&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=1wJkRHrOQWKuCmMkVqCZcBmKHwdcJRk5Vs2bg7sJSsw&m=PxCbUy8EpM7XQL78ZQAQOFTHQw13-TxY3hB4e_WrAGg&s=V_SjggSnXZqywQ715w8vEicPi-qvM0evYXQUCuNOreE&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AU3LS2P3JQXHCF4AXTKIONLTYVSVFANCNFSM5ANMSNDA&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=1wJkRHrOQWKuCmMkVqCZcBmKHwdcJRk5Vs2bg7sJSsw&m=PxCbUy8EpM7XQL78ZQAQOFTHQw13-TxY3hB4e_WrAGg&s=TYH8IDHfA8Gan6PzF2pinmbZ3ax3_6tdRr0wuUbgWQg&e=>
> .
>

======================================================================

Verizon Deutschland GmbH - Sebrathweg 20, 44149 Dortmund, Germany - Amtsgericht Dortmund, HRB 14952 - Geschäftsführer: Detlef Eppig - Vorsitzender des Aufsichtsrats: Francesco de Maio

**Comment by seratch** [comment] 2021-08-10 12:06
@EnricoVoss The fix for this issue is included in the next version - v1.10.0. I believe we can ship it by the end of this week (possibly tomorrow)

**Comment by EnricoVoss** [comment] 2021-08-10 12:10
That sounds like a plan. Thank you for your help. I will keep an eye on the
release update. Have a great day.

Kind Regards

Enrico Voss

Consultant System Engineering
Global Network and Technology
Verizon Business Group

O 004969972686460
Rebstockerstrasse 59
Germany
Frankfurt



On Tue, 10 Aug 2021 at 14:06, Kazuhiro Sera ***@***.***>
wrote:

> @EnricoVoss
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_EnricoVoss&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=1wJkRHrOQWKuCmMkVqCZcBmKHwdcJRk5Vs2bg7sJSsw&m=P7g-lay3T5MBSZGoHt6WUNFPCPFPolSgphh9n5GLFok&s=nFM1-EcdHbza3hjO5QHofbGYIbsIZdGyD_NjvoNHwXc&e=>
> The fix for this issue is included in the next version - v1.10.0. I believe
> we can ship it by the end of this week (possibly tomorrow)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_slackapi_java-2Dslack-2Dsdk_issues_784-23issuecomment-2D895972791&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=1wJkRHrOQWKuCmMkVqCZcBmKHwdcJRk5Vs2bg7sJSsw&m=P7g-lay3T5MBSZGoHt6WUNFPCPFPolSgphh9n5GLFok&s=odJdfhAXovzukaP1653U4fZq3yrmvwp6z5WvhQxkPvo&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AU3LS2MGOKZT3YJVPY7N4BTT4EI3LANCNFSM5ANMSNDA&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=1wJkRHrOQWKuCmMkVqCZcBmKHwdcJRk5Vs2bg7sJSsw&m=P7g-lay3T5MBSZGoHt6WUNFPCPFPolSgphh9n5GLFok&s=Djvyj270Tiyb6ZLheorcaPd8WvQ15H-1zCj12E_XY1c&e=>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=1wJkRHrOQWKuCmMkVqCZcBmKHwdcJRk5Vs2bg7sJSsw&m=P7g-lay3T5MBSZGoHt6WUNFPCPFPolSgphh9n5GLFok&s=T8amzMWeq-QI1MwK_n5VDyrjuf6qnkDxt3QOHfwwlxY&e=>
> or Android
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26utm-5Fcampaign-3Dnotification-2Demail&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=1wJkRHrOQWKuCmMkVqCZcBmKHwdcJRk5Vs2bg7sJSsw&m=P7g-lay3T5MBSZGoHt6WUNFPCPFPolSgphh9n5GLFok&s=Qx7WqhOrwiQhF2T2IB2o-s7VGVoj1wQ_tnXaLWENWBo&e=>
> .
>

======================================================================

Verizon Deutschland GmbH - Sebrathweg 20, 44149 Dortmund, Germany - Amtsgericht Dortmund, HRB 14952 - Geschäftsführer: Detlef Eppig - Vorsitzender des Aufsichtsrats: Francesco de Maio

**Comment by seratch** [comment] 2021-08-11 03:45
👋 v1.10.0-RC1 (release candidate) is now available in the Maven Central repositories! Try the version out if you have a chance to see the issue is resolved 🙇 We'll release v1.10.0 within a few days.

**Comment by EnricoVoss** [comment] 2021-08-11 07:46
Good day.

I still get the same error when I delete the threaded message.



Kind Regards

Enrico Voss

Consultant System Engineering
Global Network and Technology
Verizon Business Group

O 004969972686460
Rebstockerstrasse 59
Germany
Frankfurt



On Wed, 11 Aug 2021 at 05:45, Kazuhiro Sera ***@***.***>
wrote:

> 👋 v1.10.0-RC1 (release candidate) is now available in the Maven Central
> repositories! Try the version out if you have a chance to see the issue is
> resolved 🙇 We'll release v1.10.0 within a few days.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_slackapi_java-2Dslack-2Dsdk_issues_784-23issuecomment-2D896476510&d=DwMFaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=1wJkRHrOQWKuCmMkVqCZcBmKHwdcJRk5Vs2bg7sJSsw&m=AybD0dG-RVpkvRBrjauAw2qA6vpRx43Gd9KfR0bul0g&s=Wz9DdYGtpkMeyGn139oNGoig3AQrKxTloZegEj4JPWk&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AU3LS2IXWRRWWYHWTXY6LLTT4HW7FANCNFSM5ANMSNDA&d=DwMFaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=1wJkRHrOQWKuCmMkVqCZcBmKHwdcJRk5Vs2bg7sJSsw&m=AybD0dG-RVpkvRBrjauAw2qA6vpRx43Gd9KfR0bul0g&s=5abebSErb2lLOHv4szyPx5Y1gMHiz0Zk7pnAmZXDJJ4&e=>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMFaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=1wJkRHrOQWKuCmMkVqCZcBmKHwdcJRk5Vs2bg7sJSsw&m=AybD0dG-RVpkvRBrjauAw2qA6vpRx43Gd9KfR0bul0g&s=dK2A55w1sbAHHM5c72XfK4OpXnyLucrG-4hP5INvaiU&e=>
> or Android
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26utm-5Fcampaign-3Dnotification-2Demail&d=DwMFaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=1wJkRHrOQWKuCmMkVqCZcBmKHwdcJRk5Vs2bg7sJSsw&m=AybD0dG-RVpkvRBrjauAw2qA6vpRx43Gd9KfR0bul0g&s=Ek2ofqUdg3p4x0bap35kUGnHyWPkirqS5MFmWSL-ncQ&e=>
> .
>

======================================================================

Verizon Deutschland GmbH - Sebrathweg 20, 44149 Dortmund, Germany - Amtsgericht Dortmund, HRB 14952 - Geschäftsführer: Detlef Eppig - Vorsitzender des Aufsichtsrats: Francesco de Maio

**Comment by seratch** [comment] 2021-08-11 08:17
@EnricoVoss Thanks for sharing the result. 

I will check the behavior on my end too but, may I ask you to check the following again?
* Does your app use v1.10.0-RC1 version for sure?
* Does the payload causing the error have the same structure with [this test data](https://github.com/slackapi/java-slack-sdk/blob/v1.10.0-RC1/slack-api-model/src/test/java/test_locally/api/model/event/MessageChangedEventTest.java#L117-L140)? If not, could you share the difference with us? 

If the cause of the error you are currently having is not the empty array for `previous_message`, which is resolved by #791, we'll fix the new issue before releasing v1.10.0.

**Comment by seratch** [comment] 2021-08-11 08:24
@EnricoVoss I'm sorry about my previous comment. Please never mind. I figured out the issue. Will fix this in a new pull request. Thanks again for trying the version out.

**Closed** 2021-08-11 08:45 UTC
Labels: bug, project:bolt, project:slack-api-model, project:slack-app-backend

**Comment by seratch** [comment] 2021-08-11 08:57
@EnricoVoss **v1.10.0-RC2**, which fixes the issue for sure, is now available in the Sonatype OSS repositories. The jar files will be synchronized to the Maven Central very soon. Thank you very much for being patient here.

**Comment by EnricoVoss** [comment] 2021-08-11 14:15
Hi.
*1.10.0-RC2 *appears to be the winner.

Thank you for your help


Kind Regards

Enrico Voss

Consultant System Engineering
Global Network and Technology
Verizon Business Group





On Wed, 11 Aug 2021 at 10:57, Kazuhiro Sera ***@***.***>
wrote:

> @EnricoVoss
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_EnricoVoss&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=1wJkRHrOQWKuCmMkVqCZcBmKHwdcJRk5Vs2bg7sJSsw&m=Ydj9uJvoeWcm1TNk7jh0-b1aIVT1Wr5eZ50rTwAZJ3U&s=K0MhueLW4xF1eTXf7xSM5HLZ53qNiZExxFy4A86_jIs&e=>
> *v1.10.0-RC2*, which fixes the issue for sure, is now available in the
> Sonatype OSS repositories. The jar files will be synchronized to the Maven
> Central very soon. Thank you very much for being patient here.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_slackapi_java-2Dslack-2Dsdk_issues_784-23issuecomment-2D896636998&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=1wJkRHrOQWKuCmMkVqCZcBmKHwdcJRk5Vs2bg7sJSsw&m=Ydj9uJvoeWcm1TNk7jh0-b1aIVT1Wr5eZ50rTwAZJ3U&s=EGaBb8T9hWJ7TZ2XFIhnKfmijeyS89Y6KoOI_7RotjY&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AU3LS2MBJ6NNYTGT4FHAQDDT4I3RNANCNFSM5ANMSNDA&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=1wJkRHrOQWKuCmMkVqCZcBmKHwdcJRk5Vs2bg7sJSsw&m=Ydj9uJvoeWcm1TNk7jh0-b1aIVT1Wr5eZ50rTwAZJ3U&s=XgPss3k4swYcEyhB-C5D21FQZFXX42-brXrV3TE0LkM&e=>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=1wJkRHrOQWKuCmMkVqCZcBmKHwdcJRk5Vs2bg7sJSsw&m=Ydj9uJvoeWcm1TNk7jh0-b1aIVT1Wr5eZ50rTwAZJ3U&s=yeNjTAB-FNabCV00eb7_1rbM1KzVeF84wyukxJK18qg&e=>
> or Android
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26utm-5Fcampaign-3Dnotification-2Demail&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=1wJkRHrOQWKuCmMkVqCZcBmKHwdcJRk5Vs2bg7sJSsw&m=Ydj9uJvoeWcm1TNk7jh0-b1aIVT1Wr5eZ50rTwAZJ3U&s=zvA-9g7bsMMNa2SCH77moA6Ijiz8SaUGBLTOqIsI3ng&e=>
> .
>

======================================================================

Verizon Deutschland GmbH - Sebrathweg 20, 44149 Dortmund, Germany - Amtsgericht Dortmund, HRB 14952 - Geschäftsführer: Detlef Eppig - Vorsitzender des Aufsichtsrats: Francesco de Maio
