### ISSUE TITLE
java.lang.NoSuchMethodError when using RequestFormBuilder.toMultipartBody(FilesUploadRequest req)

### ISSUE THREAD

**Issue by tka4ukalex** [slackapi/java-slack-sdk#1035] opened 2022-08-24 14:19 UTC
#### The Slack SDK version

 +- com.slack.api:slack-api-client:jar:1.24.0:compile
 |  +- com.slack.api:slack-api-model:jar:1.24.0:compile
 +- com.slack.api:bolt:jar:1.24.0:compile
 |  \- com.slack.api:slack-app-backend:jar:1.24.0:compile
 +- com.slack.api:bolt-servlet:jar:1.24.0:compile
#### Java Runtime version

openjdk version "17.0.3" 2022-04-19 LTS

#### OS info

ProductName:    macOS
ProductVersion: 12.4
BuildVersion:   21F79
Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64

#### Steps to reproduce:

1) call upload slack file api
 byte[] bytes = ..... 
slackClient
              .filesUpload(request -> request
              .filename(displayName)
              .channels(List.of(slackChannelId))
              .filetype(fileType)
              .fileData(bytes)
                            )
 
#### Expected result:

200 ok

#### Actual result:

got exception :  java.lang.NoSuchMethodError: 'okhttp3.RequestBody okhttp3.RequestBody.create(byte[], okhttp3.MediaType)'

**Comment by filmaj** [comment] 2022-08-24 14:40
Hey @tka4ukalex , can you provide more context as to when you are calling this method / in what situation? It looks like you are using this within a Bolt app. Where in your bolt app are you calling the file upload method? How are you constructing `slackClient` in your example code? Please provide reproduction steps to assist me in helping you, thanks!

**Comment by tka4ukalex** [comment] 2022-08-24 14:48
I am trying to upload file to slack (using user token), other slack api work good, so 99% slack client is not the problem.
var slackClient  = Slack.getInstance();
Just trying to upload new slack file to channel and then send it with message attachments.

I see that `RequestFormBuilder.toMultipartBody(FilesUploadRequest req)` is calling this code inside 

`RequestBody file = RequestBody.create(req.getFileData(), MultipartBody.FORM);`

and there is no such method **create** with such parameters in okhttp3 RequestBody

**Comment by filmaj** [comment] 2022-08-24 16:05
I think the way you are getting a reference to the `slackClient` is incorrect. Have a look at our [API Client Basics documentation](https://slack.dev/java-slack-sdk/guides/web-api-basics). In the "Initialize Slack Object" section, it details that the `Slack.getInstance()` provides a few chainable methods - but none of them are the `filesUpload` method.

I think this code of yours:

```
Slack slackClient = Slack.getInstance();
slackClient
.filesUpload(request -> request
.filename(displayName)
.channels(List.of(slackChannelId))
.filetype(fileType)
.fileData(bytes)
);
```

... needs to be:

```
Slack slackClient = Slack.getInstance();
slackClient.methods("my-token")
.filesUpload(request -> request
.filename(displayName)
.channels(List.of(slackChannelId))
.filetype(fileType)
.fileData(bytes)
);
```

**Comment by tka4ukalex** [comment] 2022-08-24 16:16
In this thing you are right, my code example was't the most accurate, i am building the same way as you have just provided,
but the problem is how bold sdk trying to send file upload request.

in the class `RequestFormBuilder.class` there is a method

`public static MultipartBody.Builder toMultipartBody(FilesUploadRequest req) {
        MultipartBody.Builder form = new MultipartBody.Builder();

        if (req.getFileData() != null) {
            if (req.getFilename() == null) {
                req.setFilename("uploaded_file"); // filename is required for multipart/form-data
            }
            RequestBody file = RequestBody.create(req.getFileData(), MultipartBody.FORM);
            form.addFormDataPart("file", req.getFilename(), file);
        } else if (req.getFile() != null) {
            RequestBody file = RequestBody.create(req.getFile(), MultipartBody.FORM);
            form.addFormDataPart("file", req.getFilename(), file);
        }

        setIfNotNull("filetype", req.getFiletype(), form);
        setIfNotNull("filename", req.getFilename(), form);
        setIfNotNull("title", req.getTitle(), form);
        setIfNotNull("initial_comment", req.getInitialComment(), form);
        if (req.getChannels() != null) {
            setIfNotNull("channels", req.getChannels().stream().collect(joining(",")), form);
        }
        setIfNotNull("thread_ts", req.getThreadTs(), form);
        return form;
    }`
    
    and the line  1611: `RequestBody file = RequestBody.create(req.getFileData(), MultipartBody.FORM);`
    is incorrect usage or static method create

**Comment by filmaj** [comment] 2022-08-24 17:28
Hmm, I did not have this problem. I am using a recent bolt-java app, I tried with both v1.22.1 and v1.24.0 of bolt/the slack-api-client, here is my App code:

```
    App app = new App();

    app.event(AppMentionEvent.class, (payload, ctx) -> {
      AppMentionEvent event = payload.getEvent();
      ctx.client().filesUpload(req -> req
          .filename("test-upload")
          .channels(List.of(event.getChannel()))
          .filetype("txt")
          .fileData("testcontent".getBytes())
      );
      return ctx.ack();
    });
```

Here's the interaction in my test workspace:

<img width="303" alt="Screen Shot 2022-08-24 at 1 22 35 PM" src="https://user-images.githubusercontent.com/52645/186483580-cd427115-6227-469f-88da-a1c0c3a5b253.png">

And here are the (debug) logs my app generated during the file upload (using v1.22.1, but some output using v1.24.0):

```
[socket-mode-message-processor-worker-29] DEBUG com.slack.api.bolt.App - The handler started (request type: Event)
[socket-mode-message-processor-worker-29] DEBUG com.slack.api.util.http.listener.DetailedLoggingListener -
[Request URL]
POST https://slack.com/api/files.upload
[Specified Request Headers]
Authorization: (redacted)
User-Agent: Java-Slack-SDK; slack-api-client/1.22.1; OpenJDK 64-Bit Server VM/11.0.15; Mac OS X/12.5; bolt/1.22.1;
[Request Body]
--4fe4e831-60c5-47d4-943d-17233b495451
Content-Disposition: form-data; name="file"; filename="test-upload"
Content-Type: multipart/form-data
Content-Length: 11

testcontent
--4fe4e831-60c5-47d4-943d-17233b495451
Content-Disposition: form-data; name="filetype"
Content-Length: 3

txt
--4fe4e831-60c5-47d4-943d-17233b495451
Content-Disposition: form-data; name="filename"
Content-Length: 11

test-upload
--4fe4e831-60c5-47d4-943d-17233b495451
Content-Disposition: form-data; name="channels"
Content-Length: 11

C02ARJE6XNU
--4fe4e831-60c5-47d4-943d-17233b495451--


Content-Type: multipart/form-data; boundary=4fe4e831-60c5-47d4-943d-17233b495451
Content Length: 584

[Response Status]
200
[Response Body]
{"ok":true,"file":{"id":"F03V04CQN8K","created":1661361634,"timestamp":1661361634,"name":"test-upload","title":"test-upload","mimetype":"text\/plain","filetype":"text","pretty_type":"Plain Text","user":"U03G5LB1A7Q","editable":true,"size":11,"mode":"snippet","is_external":false,"external_type":"","is_public":true,"public_url_shared":false,"display_as_bot":false,"username":""}}

[socket-mode-message-processor-worker-29] DEBUG com.slack.api.bolt.App - The handler completed (request type: Event)
```

**Comment by filmaj** [comment] 2022-08-24 20:53
Also, based on the discussion in https://github.com/slackapi/java-slack-sdk/pull/544, we do not support okHTTP v3. v4.8 is the minimum version supported. As a result, I will close this issue.

**Closed by filmaj** 2022-08-24 20:53 UTC
Labels: needs info, question

**Comment by tka4ukalex** [comment] 2022-08-24 21:54
My issue was using bolt with spring boot and not providing dependency directly
`      <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
            <version>4.10.0</version>
        </dependency>`

**Comment by lee-garden** [comment] 2022-09-03 07:06
@tka4ukalex 
hi, i have same problem like you
but i cant resolve this issue with bolt
can i see your build.gradle ? ?

**Comment by tka4ukalex** [comment] 2022-09-03 10:18
@lee-garden, yes , check this link https://slack.dev/java-slack-sdk/guides/supported-web-frameworks .
With spring you will see that okhttp dependency should be present explicitly
